MyAudioApp/Controllers/MyAudioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using MyAudioApp.Models;
using PagedList;

namespace MyAudioApp.Controllers
{
    public class MyAudioController : Controller
    {
        private MyAudioDBEntities db = new MyAudioDBEntities();
      // List<SelectListItem> MyAudioTB = new List<SelectListItem>();
        public ActionResult Index(string sortOrder, string currentFilter, int? page, string searchstring)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.AlbumNameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.SongSortParm = sortOrder == "Song" ? "song_desc" : "Song";
           if(searchstring != null)
           {
               page = 1;
           }
           else
           {
               searchstring = currentFilter;
           }
           ViewBag.CurrentFilter = searchstring;

            var audio = from m in db.MyAudioTBs select m;
            if (!String.IsNullOrEmpty(searchstring))
            {
               
                audio = audio.Where(s => s.Song.Contains(searchstring));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    audio = audio.OrderByDescending(s => s.AlbumName);
                    break;
                case "Song":
                    audio = audio.OrderBy(s => s.Song);
                    break;
                case "song_desc":
                    audio = audio.OrderByDescending(s => s.Song);        
                    break;
                case "albumBy":
                    audio = audio.OrderBy(s => s.AlbumBy);
                    break;
                case "label":
                    audio = audio.OrderBy(s => s.Label);
                    break;
                case "filename":
                    audio = audio.OrderBy(s => s.Filename);
                    break;
                default:  // Name ascending 
                    audio = audio.OrderBy(s => s.AlbumName);
                    break;
            }
            int pageSize = 4;
            int pageNumber = (page ?? 1);
            return View(audio.ToPagedList(pageNumber, pageSize));
        }

        //
        // GET: /MyAudio/Details/5

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            MyAudioTB audio = db.MyAudioTBs.Find(id);
            if(audio == null )
            {
                return HttpNotFound();
            }
            return View(audio);
        }

        //
        // GET: /MyAudio/Create

        public ActionResult Create()
        {
            ViewBag.MyAudioTB = db.MyAudioTBs.ToList();
            //ViewData["Message"] = "Success";
            return View();
        }

        //
        // POST: /MyAudio/Create
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Create([Bind(Exclude = "id")] MyAudioTB audiotocreate, HttpPostedFileBase file) 
        {
            ViewBag.MyAudioTB = db.MyAudioTBs.ToList();
            if(!ModelState.IsValid )
                 return View();

            try
            {
                if (file.ContentLength > 0)
                {
                    var filename = System.IO.Path.GetFileName(file.FileName);        
                    var path = System.IO.Path.Combine(Server.MapPath("~/Audio"), filename);                    
                    file.SaveAs(path);
                    audiotocreate.UserName = User.Identity.Name;
                    audiotocreate.Filename = filename;                   
                    db.MyAudioTBs.Add(audiotocreate);
                    db.SaveChanges();
                  
                }
                TempData["Success"] = "you have uploaded song successfully";
                return RedirectToAction("Index");
            }
            catch
            {
                ViewData["ErrorUploading"] = "Upload failed";
                return View();
            }
        }
    
        // GET: /MyAudio/Edit/5

        public ActionResult Edit(int id = 0)
        {
            MyAudioTB audiotoedit = db.MyAudioTBs.Find(id);
            if(audiotoedit == null )
            {
                return HttpNotFound();
            }
            return View(audiotoedit);
        }

        //
        // POST: /MyAudio/Edit/5

        [HttpPost]
        public ActionResult Edit(MyAudioTB audiotoedit)
        {
            if (ModelState.IsValid)
            {
                db.Entry(audiotoedit).State = System.Data.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("index");
            }
            return View(audiotoedit);
        }

        //
        // GET: /MyAudio/Delete/5

        public ActionResult Delete(int? id)
        {
            if(id == null )
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            MyAudioTB audio = db.MyAudioTBs.Find(id);
            if(audio == null )
            {
                return HttpNotFound();
            }

            return View(audio);
        }

        //
        // POST: /MyAudio/Delete/5

        [HttpPost,ActionName ("Delete")]
    [ValidateAntiForgeryToken ]
        public ActionResult DeleteConfirmed(int id)
        {
            MyAudioTB audio = db.MyAudioTBs.Find(id);
            db.MyAudioTBs.Remove(audio);
            var path = System.IO.Path.Combine(Server.MapPath("~/Audio"), audio.Filename);
            if (System.IO.File.Exists(path))
            {
                System.IO.File.Delete(path);
            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        //
        // GET: /MyAudio/Player/12

        public ActionResult Player(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            MyAudioTB audio = db.MyAudioTBs.Find(id);
            if (audio == null)
            {
                return HttpNotFound();
            }
            return View(audio);
           
        }       
    }
}

MyAudioApp/Views/MyAudio/About.cshtml
@model MyAudioApp.Models.MyAudioTB

@{
    ViewBag.Title = "About";
}

<h2>About</h2>


this is my about page

MyAudioApp/Views/MyAudio/Create.cshtml
@model MyAudioApp.Models.MyAudioTB
@*@model IEnumerable<MyAudioApp.Models.MyAudioTB>*@           
@{
    ViewBag.Title = "Create";
   
}
   
    <h2>Create</h2>
@if (ViewData["ErrorUploading"] != null)
{
    <div class="red">
      <p><strong>ErrorUploading:</strong>@ViewData["ErrorUploading"].ToString()</p>
    </div>
} 
@if (TempData["Success"] != null)
{
    <div class="green">
      <p><strong>Success:</strong>@TempData["Success"].ToString()</p>
    </div>
}

    @using (Html.BeginForm("Create", "MyAudio", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        <fieldset>
            <legend>MyAudioTB</legend>
            <div class="editor-label">
                @Html.LabelFor(model => model.AlbumName)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.AlbumName)
                @Html.DropDownListFor(model => model.Id, new SelectList(ViewBag.MyAudioTB, "Id", "AlbumName"), "Select Album Name")
                @Html.ValidationMessageFor(model => model.AlbumName)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Song)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Song)
                @Html.ValidationMessageFor(model => model.Song)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.AlbumBy)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.AlbumBy)
                @Html.ValidationMessageFor(model => model.AlbumBy)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Label)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Label)
                @Html.ValidationMessageFor(model => model.Label)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Filename)
            </div>
            <div class="editor-field">
                @Html.TextBox("file", "", new { type = "file" })
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.UserName)
            </div>
            <div class="editor-field">
                @Html.ValidationMessageFor(model => model.UserName)
            </div>

            <strong>@User.Identity.Name</strong>

            <p>
                <input type="submit" value="Create" />
            </p>
        </fieldset>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

MyAudioApp/Views/MyAudio/Delete.cshtml
@model MyAudioApp.Models.MyAudioTB

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>MyAudioTB</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.AlbumName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.AlbumName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Song)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Song)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.AlbumBy)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.AlbumBy)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Label)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Label)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Filename)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Filename)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

MyAudioApp/Views/MyAudio/Details.cshtml
@model MyAudioApp.Models.MyAudioTB

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>MyAudioTB</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.AlbumName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.AlbumName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Song)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Song)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.AlbumBy)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.AlbumBy)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Label)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Label)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Filename)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Filename)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MyAudioApp/Views/MyAudio/Edit.cshtml
@model MyAudioApp.Models.MyAudioTB

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>MyAudioTB</legend>

        @Html.HiddenFor(model => model.Id)

        <div class="editor-label">
            @Html.LabelFor(model => model.AlbumName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.AlbumName)
            @Html.ValidationMessageFor(model => model.AlbumName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Song)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Song)
            @Html.ValidationMessageFor(model => model.Song)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.AlbumBy)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.AlbumBy)
            @Html.ValidationMessageFor(model => model.AlbumBy)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Label)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Label)
            @Html.ValidationMessageFor(model => model.Label)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Filename)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Filename)
            @Html.ValidationMessageFor(model => model.Filename)
        </div>


        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MyAudioApp/Views/MyAudio/Index.cshtml
@*@model IEnumerable<MyAudioApp.Models.MyAudioTB>*@
@model PagedList.IPagedList<MyAudioApp.Models.MyAudioTB>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Index";
    
   
}

<h2>Index</h2>
@if (TempData["Success"] != null)
{
    <div class="green">
        <p><strong>Success:</strong>@TempData["Success"].ToString()</p>
    </div>
}

    @Html.ActionLink("Upload New", "Create")
    @using (Html.BeginForm("Index", "MyAudio", FormMethod.Get))
    {
    <p>
       Search By Song: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value=" Search" />

    </p>
     }


<table>
 
   <tr>
        <th>
          @Html.ActionLink("AlbumName", "Index", new { sortOrder = ViewBag.AlbumNameSortParm, currentFilter=ViewBag.CurrentFilter })  
        </th>
        <th>
            
           @Html.ActionLink("Song", "Index", new { sortOrder = ViewBag.SongSortParm, currentFilter=ViewBag.CurrentFilter })
        </th>
        <th>
            AlbumBy
        </th>
        <th>
            Label
        </th>
        <th>
           Filename
        </th>
        <th>
            UserName
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.AlbumName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Song)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AlbumBy)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Label)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Filename)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id }) |
            @Html.ActionLink("Play", "Player", new { id=item.Id })
        </td>
    </tr>
   
}

</table>
<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index", new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))

MyAudioApp/Views/MyAudio/Player.cshtml
@model MyAudioApp.Models.MyAudioTB

@{
    ViewBag.Title = "Player";
}

<h2>Player</h2>

<fieldset>
    <legend>MyAudioTB</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.AlbumName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.AlbumName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Song)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Song)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.AlbumBy)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.AlbumBy)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Label)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Label)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Filename)
    </div>
    <div class="display-field">
       @Html.DisplayFor(model => model.Filename)
    </div>
    <audio controls>
        <source src= "@Url.Content("~/Audio/" + Model.Filename)" type="audio/mpeg">
        Your browser does not support the audio element.
    </audio>
   
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MyAudioApp/Views/MyAudio/Register.cshtml
@model MyAudioApp.Models.RegisterModel
@{
    ViewBag.Title = "Register";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>Create a new account.</h2>
</hgroup>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary()

    <fieldset>
        <legend>Registration Form</legend>
        <ol>
            <li>
                @Html.LabelFor(m => m.UserName)
                @Html.TextBoxFor(m => m.UserName)
            </li>
            <li>
                @Html.LabelFor(m => m.Password)
                @Html.PasswordFor(m => m.Password)
            </li>
            <li>
                @Html.LabelFor(m => m.ConfirmPassword)
                @Html.PasswordFor(m => m.ConfirmPassword)
            </li>
        </ol>
        <input type="submit" value="Register" />
    </fieldset>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MyAudioApp/Views/MyAudio/Upload.cshtml
@model MyAudioApp.Models.MyAudioTB

@{
    ViewBag.Title = "Upload";
}

<h2>Upload</h2>